Repository bloomberg/blazingmq, pull requests merged in 2023-08, with the labels that each got.

#51 Add clang formatting checks for src/ files
  .clang-format
  .github/workflows/build.yaml
  src/groups/bmq/bmqa/bmqa_mocksession.cpp
  src/groups/bmq/bmqa/bmqa_mocksession.t.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.cpp
  src/groups/bmq/bmqp/bmqp_queueid.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterorchestrator.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_messagegroupidmanager.cpp
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.cpp
  src/groups/mqb/mqbblp/mqbblp_queuehandle.h
  src/groups/mqb/mqbblp/mqbblp_queuehandlecatalog.cpp
  src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.cpp
  src/groups/mqb/mqbblp/mqbblp_routers.h
  src/groups/mqb/mqbblp/mqbblp_routers.t.cpp
  src/groups/mqb/mqbc/mqbc_clusternodesession.cpp
  src/groups/mqb/mqbcfg/mqbcfg_messages.cpp
  src/groups/mqb/mqbcfg/mqbcfg_messages.h
  src/groups/mqb/mqbs/mqbs_filestore.t.cpp
  src/groups/mwc/mwcc/mwcc_twokeyhashmap.h
  src/groups/mwc/mwcex/mwcex_executionproperty.h
  src/groups/mwc/mwcex/mwcex_executionutil.h
  src/groups/mwc/mwcex/mwcex_executortraits.h
  src/groups/mwc/mwcex/mwcex_future.h
  src/groups/mwc/mwcu/mwcu_weakmemfn.h
Labels: A-Other

#58 Add checks for DCO signoff
  .github/workflows/sanity-check.yaml
Labels: enhancement, A-Other

#34 build-ubuntu script
  bin/build-ubuntu.sh
  docs/docs/getting_started/blazingmq_in_action.md
Labels: A-Build

#54 Add build script
  bin/build-darwin.sh
Labels: A-Build

#59 Fix: thread race in bmqimp_brokersession.t.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.t.cpp
Labels: A-Testing

#78 Create CODEOWNERS
  .github/CODEOWNERS
Labels: A-Other

#77 Add more license notices
  licenses-binary/LICENSE-bde.txt
  licenses-binary/LICENSE-bison-skeleton.txt
  licenses-binary/LICENSE-flex.txt
  licenses-binary/LICENSE-ntf-core.txt
  licenses-binary/LICENSE-zlib.txt
  licenses/LICENSE-bde.txt
  licenses/LICENSE-ntf-core.txt
Labels: enhancement, A-Other

#83 Fix: disable default allocator check for mwcex_bdlmtfixedthreadpoolexecutor
  docker/build_deps.sh
  src/groups/mwc/mwcex/mwcex_bdlmtfixedthreadpoolexecutor.t.cpp
Labels: bug, A-Testing
