Repository bloomberg/blazingmq, pull requests merged in 2023-11, with the labels that each got.

#144 Rename sanity check to more descriptive DCO check
  .github/workflows/dco-check.yaml
Labels: A-Other

#135 Generating unique Subscription ids for each request
  src/applications/bmqtool/m_bmqtool_inpututil.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.h
  src/groups/bmq/bmqimp/bmqimp_event.h
  src/groups/bmq/bmqimp/bmqimp_messagedumper.cpp
  src/groups/bmq/bmqimp/bmqimp_messagedumper.t.cpp
  src/groups/bmq/bmqimp/bmqimp_queue.cpp
  src/groups/bmq/bmqimp/bmqimp_queue.h
  src/groups/bmq/bmqimp/bmqimp_queuemanager.cpp
  src/groups/bmq/bmqimp/bmqimp_queuemanager.h
  src/groups/bmq/bmqp/bmqp_optionsview.h
  src/groups/bmq/bmqp/bmqp_protocol.h
  src/groups/bmq/bmqt/bmqt_subscription.cpp
  src/groups/bmq/bmqt/bmqt_subscription.h
  src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
Labels: bug

#145 Add module for figuring out alternate package providers
  CMakeLists.txt
  etc/cmake/BmqPackageProvider.cmake
Labels: A-Build

#149 docs: Remove references to Python SDK shortly being open sourced
  README.md
  docs/docs/introduction/overview.md
  docs/docs/introduction/roadmap.md
Labels: documentation, A-Docs

#150 docs: Prevent Jekyll from mangling our Sphinx documentation
  docs/docs/apidocs/python_apidocs/.nojekyll
Labels: documentation, A-Docs

#151 docs: Teach Jekyll to directly include generated Python docs
  docs/_config.yml
  docs/docs/apidocs/python_apidocs/.nojekyll
Labels: documentation, A-Docs

#155 docs: Update `SessionOptions` accessors’ and manipulators’ docs
  src/groups/bmq/bmqt/bmqt_sessionoptions.h
Labels: documentation, A-Docs

#154 Fix: MockSession example and default allocator [172764384]
  src/groups/bmq/bmqa/bmqa_mocksession.cpp
  src/groups/bmq/bmqa/bmqa_mocksession.h
Labels: A-Client

#143 Update vcpkg building docs
  README.md
Labels: documentation, A-Build

#156 re-insert queue tracking if needed
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
Labels: bug
