Repository bloomberg/blazingmq, pull requests merged in 2023-09, with the labels that each got.

#107 Fixup README for Just the Docs documentation website
  docs/README.md
  docs/_config.yml
  licenses/LICENSE-just-the-docs.txt
Labels: documentation, A-Docs

#113 Small fixes
  src/applications/bmqbrkr/etc/clusters.json
  src/groups/mqb/mqbcfg/mqbcfg.xsd
Labels: A-Broker

#111 Publish a broker image on release
  .github/workflows/publish.yaml
Labels: A-Other

#115 Fix: ClientSession description during QueueHandle finalization
  .gitignore
  src/groups/mqb/mqba/mqba_clientsession.cpp
  src/groups/mqb/mqba/mqba_clientsession.h
Labels: bug, A-Broker

#112 Add support for building with vcpkg
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  README.md
  vcpkg-configuration.json
  vcpkg.json
Labels: enhancement, A-Other
