Repository bloomberg/blazingmq, pull requests merged in 2024-01, with the labels that each got.

#171 Build ntf-core without `-Werror`
  bin/build-darwin.sh
  bin/build-ubuntu.sh
Labels: bug, A-Build

#183 mwcu::BlobIterator: remove bsl::iterator inheritance
  src/groups/mwc/mwcu/mwcu_blobiterator.h
Labels: enhancement, A-Other

#184 Rejecting incoming connections w/o URI
  src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp
Labels: bug
