Repository bloomberg/blazingmq, pull requests merged in 2024-10, with the labels that each got.

#334 Feat[MQB]: Monolithic Virtual Storage
  src/groups/mqb/mqba/mqba_application.cpp
  src/groups/mqb/mqba/mqba_application.h
  src/groups/mqb/mqbblp/mqbblp_cluster.cpp
  src/groups/mqb/mqbblp/mqbblp_cluster.h
  src/groups/mqb/mqbblp/mqbblp_clustercatalog.cpp
  src/groups/mqb/mqbblp/mqbblp_clustercatalog.h
  src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterproxy.h
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_pushstream.cpp
  src/groups/mqb/mqbblp/mqbblp_pushstream.h
  src/groups/mqb/mqbblp/mqbblp_pushstream.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queue.cpp
  src/groups/mqb/mqbblp/mqbblp_queue.h
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queueenginetester.cpp
  src/groups/mqb/mqbblp/mqbblp_queueenginetester.h
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.h
  src/groups/mqb/mqbblp/mqbblp_queuestate.cpp
  src/groups/mqb/mqbblp/mqbblp_queuestate.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.t.cpp
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
  src/groups/mqb/mqbblp/mqbblp_remotequeue.h
  src/groups/mqb/mqbblp/mqbblp_remotequeue.t.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.h
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.t.cpp
  src/groups/mqb/mqbblp/mqbblp_routers.cpp
  src/groups/mqb/mqbblp/mqbblp_routers.h
  src/groups/mqb/mqbblp/mqbblp_routers.t.cpp
  src/groups/mqb/mqbblp/package/mqbblp.mem
  src/groups/mqb/mqbc/mqbc_clusterdata.cpp
  src/groups/mqb/mqbc/mqbc_clusterdata.h
  src/groups/mqb/mqbi/mqbi_cluster.h
  src/groups/mqb/mqbi/mqbi_queueengine.cpp
  src/groups/mqb/mqbi/mqbi_queueengine.h
  src/groups/mqb/mqbi/mqbi_storage.h
  src/groups/mqb/mqbmock/mqbmock_cluster.cpp
  src/groups/mqb/mqbmock/mqbmock_cluster.h
  src/groups/mqb/mqbs/mqbs_filebackedstorage.cpp
  src/groups/mqb/mqbs/mqbs_filebackedstorage.h
  src/groups/mqb/mqbs/mqbs_filestore.cpp
  src/groups/mqb/mqbs/mqbs_inmemorystorage.cpp
  src/groups/mqb/mqbs/mqbs_inmemorystorage.h
  src/groups/mqb/mqbs/mqbs_inmemorystorage.t.cpp
  src/groups/mqb/mqbs/mqbs_storageprintutil.t.cpp
  src/groups/mqb/mqbs/mqbs_virtualstorage.cpp
  src/groups/mqb/mqbs/mqbs_virtualstorage.h
  src/groups/mqb/mqbs/mqbs_virtualstorage.t.cpp
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.cpp
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.h
  src/groups/mqb/mqbs/mqbs_voidstorageiterator.cpp
  src/groups/mqb/mqbs/mqbs_voidstorageiterator.h
  src/groups/mqb/mqbs/mqbs_voidstorageiterator.t.cpp
  src/groups/mqb/mqbs/package/mqbs.mem
  src/integration-tests/test_breathing.py
  src/integration-tests/test_subscriptions.py
Labels: enhancement

#444 Docs[BMQ]: Use `.dox` files rather than `.md` files
  Doxyfile
  src/groups/bmq/bmqa/README.dox
  src/groups/bmq/bmqpi/README.dox
  src/groups/bmq/bmqt/README.dox
Labels: bug, documentation, A-Client, A-Docs

#459 Fix[bmqeval]: Allow dots in subscription property names
  src/groups/bmq/bmqeval/bmqeval_simpleevaluator.t.cpp
  src/groups/bmq/bmqeval/bmqeval_simpleevaluatorscanner.l
Labels: enhancement, A-Broker, A-Client

#467 Fix[mqbblp]: clean app subscriptions on reconfigure
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
Labels: bug

#472 fix: enhanced detection of duplciate PUSHes
  src/groups/mqb/mqbblp/mqbblp_pushstream.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
Labels: bug

#491 Docs: Fix `bmqa_mocksession` doxygen failure
  src/groups/bmq/bmqa/bmqa_mocksession.h
Labels: documentation, A-Docs
