Repository bloomberg/blazingmq, pull requests merged in 2024-05, with the labels that each got.

#275 Handle out-of-order Configure responses
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
Labels: bug

#283 explicitly call gc when not idle
  src/groups/mqb/mqbblp/mqbblp_storagemanager.cpp
  src/groups/mqb/mqbc/mqbc_storagemanager.cpp
  src/groups/mqb/mqbs/mqbs_filestore.cpp
Labels: bug

#285 Add link to python sdk
  README.md
Labels: documentation

#286 Remove horizontal rules from README
  README.md
Labels: documentation

#296 Remove extraneous space from mqbc_clusterstate
  src/groups/mqb/mqbc/mqbc_clusterstate.h
Labels: enhancement, A-Broker

#295 AppConfig/advertiseSubscriptions as a safety switch for SDK
  src/groups/bmq/bmqp/bmqp_protocol.cpp
  src/groups/bmq/bmqp/bmqp_protocol.h
  src/groups/mqb/mqba/mqba_sessionnegotiator.cpp
  src/groups/mqb/mqbcfg/mqbcfg.xsd
  src/groups/mqb/mqbcfg/mqbcfg_messages.cpp
  src/groups/mqb/mqbcfg/mqbcfg_messages.h
Labels: enhancement

#301 configureStream if broker negotiates it
  src/groups/bmq/bmqimp/bmqimp_brokersession.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.h
  src/groups/bmq/bmqimp/bmqimp_brokersession.t.cpp
  src/groups/bmq/bmqimp/bmqimp_negotiatedchannelfactory.cpp
  src/groups/bmq/bmqimp/bmqimp_negotiatedchannelfactory.h
Labels: enhancement

#311 Fix: Update auto subscription configuration schema documentation
  src/groups/mqb/mqbconfm/mqbconf.xsd
Labels: bug, documentation, A-Broker, A-Docs
