Repository bloomberg/blazingmq, pull requests merged in 2024-11, with the labels that each got.

#503 Build: Teach build system to build Doxygen docs
  CMakeLists.txt
Labels: documentation, A-Docs, A-Build

#519 Fix[bmqa]: Remove unused `Session::impl()` function
  src/groups/bmq/bmqa/bmqa_session.h
Labels: A-Client

#522 Refactor[mqba]: Remove unused `d_scriptTimestamp` from domain resolver cache
  src/groups/mqb/mqba/mqba_domainresolver.h
Labels: A-Broker

#528 fix PushStream & VirtualStorage ordinal
  src/groups/mqb/mqbblp/mqbblp_pushstream.cpp
  src/groups/mqb/mqbblp/mqbblp_pushstream.h
  src/groups/mqb/mqbblp/mqbblp_pushstream.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.cpp
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.h
Labels: bug
