Repository bloomberg/blazingmq, pull requests merged in 2025-09, with the labels that each got.

#912 docs: Generate Doxygen tag files
  CMakeLists.txt
Labels: A-Docs, A-Build

#931 Fix[MQB]: process assignment failure in a loop
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
Labels: bug

#932 Fix[MQB]: always attempt to process pending open queue requests
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
Labels: bug

#942 Fix[bmqeval]: Correctly store eval error code
  src/groups/bmq/bmqeval/bmqeval_simpleevaluator.cpp
Labels: bug, A-Broker
