Repository bloomberg/blazingmq, pull requests merged in 2025-02, with the labels that each got.

#597 fix Replica ignores duplicate broadcast PUSH
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
Labels: bug

#598 fix race between restoreState and onOpenQueueResponse [178106131]
  src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
Labels: bug

#611 Fix[bmqstoragetool]: Fix class header comment
  src/applications/bmqstoragetool/m_bmqstoragetool_messagedetails.cpp
Labels: enhancement, A-Other

#612 feat DEAD channel detection, now is everywhere
  docker/cluster/config/bmqbrkrcfg.json
  docker/single-node/config/bmqbrkrcfg.json
  src/applications/bmqbrkr/etc/bmqbrkrcfg.json
  src/groups/bmq/bmqimp/bmqimp_application.cpp
  src/groups/bmq/bmqimp/bmqimp_application.h
  src/groups/bmq/bmqimp/bmqimp_brokersession.cpp
  src/groups/bmq/bmqimp/bmqimp_brokersession.h
  src/groups/bmq/bmqimp/bmqimp_negotiatedchannelfactory.cpp
  src/groups/bmq/bmqimp/bmqimp_negotiatedchannelfactory.h
  src/groups/bmq/bmqp/bmqp_ctrlmsg.xsd
  src/groups/bmq/bmqp/bmqp_ctrlmsg_messages.cpp
  src/groups/bmq/bmqp/bmqp_ctrlmsg_messages.h
  src/groups/bmq/bmqp/bmqp_heartbeatmonitor.cpp
  src/groups/bmq/bmqp/bmqp_heartbeatmonitor.h
  src/groups/bmq/bmqp/package/bmqp.mem
  src/groups/mqb/mqba/mqba_sessionnegotiator.cpp
  src/groups/mqb/mqba/mqba_sessionnegotiator.h
  src/groups/mqb/mqbnet/mqbnet_negotiator.h
  src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp
  src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.h
  src/integration-tests/test_heartbeat.py
  src/python/blazingmq/dev/configurator/__init__.py
Labels: enhancement

#585 fix: Not delivering old data to new Apps
  src/groups/bmq/bmqc/bmqc_orderedhashmap.h
  src/groups/mqb/mqbblp/mqbblp_domain.h
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.t.cpp
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbc/mqbc_clusterstate.cpp
  src/groups/mqb/mqbc/mqbc_clusterstate.h
  src/groups/mqb/mqbc/mqbc_clusterutil.cpp
  src/groups/mqb/mqbc/mqbc_storagemanager.cpp
  src/groups/mqb/mqbc/mqbc_storageutil.cpp
  src/groups/mqb/mqbc/mqbc_storageutil.h
  src/groups/mqb/mqbi/mqbi_clusterstatemanager.h
  src/groups/mqb/mqbi/mqbi_storage.cpp
  src/groups/mqb/mqbi/mqbi_storage.h
  src/groups/mqb/mqbs/mqbs_datastore.cpp
  src/groups/mqb/mqbs/mqbs_datastore.h
  src/groups/mqb/mqbs/mqbs_filebackedstorage.cpp
  src/groups/mqb/mqbs/mqbs_filebackedstorage.h
  src/groups/mqb/mqbs/mqbs_filebackedstorage.t.cpp
  src/groups/mqb/mqbs/mqbs_filestore.cpp
  src/groups/mqb/mqbs/mqbs_filestore.h
  src/groups/mqb/mqbs/mqbs_filestore.t.cpp
  src/groups/mqb/mqbs/mqbs_filestoreprotocol.h
  src/groups/mqb/mqbs/mqbs_filestoreprotocolprinter.cpp
  src/groups/mqb/mqbs/mqbs_filestoreprotocolutil.cpp
  src/groups/mqb/mqbs/mqbs_filestoreprotocolutil.h
  src/groups/mqb/mqbs/mqbs_filestoreprotocolutil.t.cpp
  src/groups/mqb/mqbs/mqbs_inmemorystorage.cpp
  src/groups/mqb/mqbs/mqbs_inmemorystorage.h
  src/groups/mqb/mqbs/mqbs_inmemorystorage.t.cpp
  src/groups/mqb/mqbs/mqbs_replicatedstorage.h
  src/groups/mqb/mqbs/mqbs_virtualstorage.cpp
  src/groups/mqb/mqbs/mqbs_virtualstorage.h
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.cpp
  src/groups/mqb/mqbs/mqbs_virtualstoragecatalog.h
  src/integration-tests/test_appids.py
Labels: enhancement

#620 fix Remove storage not found when removing queue
  src/groups/mqb/mqbc/mqbc_storageutil.cpp
Labels: enhancement

#624 Fix[MQB]: placate error log on ShutdownV2
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
Labels: enhancement

#629 CI: Publish container images to GHCR.io
  .github/workflows/publish.yaml
Labels: A-Build

#630 Fix: Publish last stage, not “simple” stage to GHCR
  .github/workflows/publish.yaml
Labels: bug, A-Build
