Repository bloomberg/blazingmq, pull requests merged in 2025-04, with the labels that each got.

#674 Fix: Using genCount for lastPush
  src/groups/mqb/mqbblp/mqbblp_pushstream.h
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbstat/mqbstat_queuestats.cpp
Labels: bug

#675 Fix; not switching thread context when closing on shutdown
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
Labels: bug

#596 feat repair CSL on mismatch with Domain config
  src/groups/mqb/mqbblp/mqbblp_cluster.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterorchestrator.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterorchestrator.h
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
  src/groups/mqb/mqbblp/mqbblp_clusterstatemanager.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterstatemanager.h
  src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.h
  src/groups/mqb/mqbblp/mqbblp_storagemanager.cpp
  src/groups/mqb/mqbblp/mqbblp_storagemanager.h
  src/groups/mqb/mqbc/mqbc_clusterstate.cpp
  src/groups/mqb/mqbc/mqbc_clusterstate.h
  src/groups/mqb/mqbc/mqbc_clusterstatemanager.cpp
  src/groups/mqb/mqbc/mqbc_clusterstatemanager.h
  src/groups/mqb/mqbc/mqbc_clusterutil.cpp
  src/groups/mqb/mqbc/mqbc_clusterutil.h
  src/groups/mqb/mqbc/mqbc_clusterutil.t.cpp
  src/groups/mqb/mqbc/mqbc_storagemanager.cpp
  src/groups/mqb/mqbc/mqbc_storagemanager.t.cpp
  src/groups/mqb/mqbc/mqbc_storageutil.cpp
  src/groups/mqb/mqbc/mqbc_storageutil.h
  src/groups/mqb/mqbi/mqbi_clusterstatemanager.h
  src/groups/mqb/mqbi/mqbi_storagemanager.h
  src/groups/mqb/mqbs/mqbs_storageprintutil.cpp
  src/groups/mqb/mqbs/mqbs_storageprintutil.h
  src/integration-tests/test_appids.py
Labels: enhancement

#690 Fix: Disable linux/arm builds on Docker publish
  .github/workflows/publish.yaml
Labels: bug, A-Build

#684 fix: inlining closeQueue on shutdown
  src/groups/mqb/mqbblp/mqbblp_cluster.h
  src/groups/mqb/mqbblp/mqbblp_clusterproxy.h
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbi/mqbi_cluster.h
  src/groups/mqb/mqbmock/mqbmock_cluster.h
Labels: bug

#685 Test: Remove `all.td` target
  etc/cmake/BMQTest.cmake
Labels: A-Testing

#708 fixing CS shutdown V2
  src/groups/mqb/mqba/mqba_clientsession.cpp
  src/groups/mqb/mqba/mqba_clientsession.h
Labels: bug
