Repository bloomberg/blazingmq, pull requests merged in 2025-01, with the labels that each got.

#557 Fix[build]: Remove `docs` target as a dependency of `all`
  CMakeLists.txt
Labels: bug, A-Docs, A-Build

#552 fix: RemoteQueue handles duplicates
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
Labels: bug

#551 fix: protecting RemoteQueue::expirePendingMessagesDispatched
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
  src/groups/mqb/mqbblp/mqbblp_remotequeue.h
Labels: bug

#553 Fix: handling no leader case
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
Labels: bug

#428 Fix[MQB]: app refcount is numVirtualStorages
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
Labels: bug

#571 Misc[mqbc]: Move `mqbc_clusterstate.t.cpp` into proper directory
  src/groups/mqb/mqbc/mqbc_clusterstate.t.cpp
Labels: A-Testing

#583 Fix[bmq]: Flush output on test and contract failures
  src/groups/bmq/bmqtst/bmqtst_testhelper.h
Labels: bug, A-Testing
