Repository bloomberg/blazingmq, pull requests merged in 2025-07, with the labels that each got.

#736 Fix[MQBBLP] Refactor logic of consumption monitor
  src/groups/mqb/mqbblp/mqbblp_clusterorchestrator.cpp
  src/groups/mqb/mqbblp/mqbblp_localqueue.cpp
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.cpp
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.h
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.cpp
  src/groups/mqb/mqbblp/mqbblp_queueengineutil.h
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_relayqueueengine.h
  src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
  src/groups/mqb/mqbblp/mqbblp_rootqueueengine.h
  src/groups/mqb/mqbi/mqbi_queueengine.h
  src/groups/mqb/mqbmock/mqbmock_queueengine.cpp
  src/groups/mqb/mqbmock/mqbmock_queueengine.h
  src/integration-tests/test_alarms.py
Labels: enhancement

#814 Fix: Require latency monitoring domain to match prefix
  src/groups/mqb/mqbc/mqbc_clusterutil.cpp
  src/groups/mqb/mqbcfg/mqbcfg.xsd
Labels: bug, A-Broker

#820 Fix[mqba::ClientSession]: use WeakMemFn to avoid crashes on teardown
  src/groups/mqb/mqba/mqba_clientsession.cpp
Labels: bug

#822 Fix[mqbblp::Domain]: thread safety on shutdown
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
  src/groups/mqb/mqbblp/mqbblp_queue.cpp
  src/groups/mqb/mqbblp/mqbblp_queue.h
Labels: bug

#813 Feat[bmqtool]: add autoPubSubModulo parameter to test subscriptions
  src/applications/bmqtool/bmqtool.m.cpp
  src/applications/bmqtool/bmqtoolcmd.xsd
  src/applications/bmqtool/m_bmqtool_application.cpp
  src/applications/bmqtool/m_bmqtool_inpututil.cpp
  src/applications/bmqtool/m_bmqtool_inpututil.h
  src/applications/bmqtool/m_bmqtool_interactive.cpp
  src/applications/bmqtool/m_bmqtool_messages.cpp
  src/applications/bmqtool/m_bmqtool_messages.h
  src/applications/bmqtool/m_bmqtool_parameters.cpp
  src/applications/bmqtool/m_bmqtool_parameters.h
  src/applications/bmqtool/m_bmqtool_poster.cpp
Labels: enhancement

#827 Refactor[MQB]: simplify queue creation/registration
  src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
  src/groups/mqb/mqbblp/mqbblp_domain.cpp
  src/groups/mqb/mqbblp/mqbblp_domain.h
  src/groups/mqb/mqbblp/mqbblp_queue.cpp
  src/groups/mqb/mqbblp/mqbblp_queueconsumptionmonitor.t.cpp
  src/groups/mqb/mqbblp/mqbblp_queueenginetester.cpp
  src/groups/mqb/mqbi/mqbi_domain.h
  src/groups/mqb/mqbmock/mqbmock_domain.cpp
  src/groups/mqb/mqbmock/mqbmock_domain.h
Labels: enhancement
